name: Update CSV

on:
  workflow_dispatch:  # Manual trigger from GitHub UI

jobs:
  update_csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run CSV update script
        run: node node_test/index.js

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add node_test/data.csv
          git commit -m "Update CSV via GitHub Actions" || echo "No changes to commit"
          git push
